// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://binidmnyohoucctwqpol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJpbmlkbW55b2hvdWNjdHdxcG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4NjcxNjMsImV4cCI6MjA2MDQ0MzE2M30.Fm-wVae7hEXOx_cabFmOEz5JJGYx68s2mGda2YLz69s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);